name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          registry: ${{ secrets.CUSTOM_REGISTRY }}
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ secrets.CUSTOM_REGISTRY }}/pilgrim:latest
      - name: Inspect
        run: docker buildx imagetools inspect ${{ secrets.CUSTOM_REGISTRY }}/pilgrim:latest
