name: ci

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.CUSTOM_REGISTRY }}/pilgrim
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Custom Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CUSTOM_REGISTRY }}
          username: ${{ secrets.DOCKERREG_USERNAME }}
          password: ${{ secrets.DOCKERREG_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.CUSTOM_REGISTRY }}/pilgrim:latest
          cache-to: type=inline
      - name: Inspect
        if: github.event_name != 'pull_request'
        run: docker buildx imagetools inspect ${{ secrets.CUSTOM_REGISTRY }}/pilgrim:latest
